### PR TITLE
Add requests limit

### PR DESCRIPTION
**Pull request by Kr00lIX**
When I was using your library I faced the necessity to limit requests for google API. 
Maybe that could be helpful for someone else.

### CODE REVIEW

**Comment by Voronchuk** [comment]
I'll test it more over this week and add more feedback if needed.

**Comment by Kr00lIX** [comment]
Thanks for the review @Voronchuk ! Pushed an update for all the things you mentioned.

**Comment by Voronchuk** [comment]
From time to time as was getting the following errors:

```
1) test clear batched for 2 rows in list (GSS.SpreadsheetListTest)
     test/elixir_google_spreadsheets/spreadsheet_list_test.exs:75
     ** (exit) exited in: GenServer.call(#PID<0.359.0>, {:clear_rows, ["A1:E1", "A2:E2"], []}, 5000)
         ** (EXIT) an exception was raised:
             ** (WithClauseError) no with clause matching: {:ok, %HTTPoison.Response{body: "{\n  \"error\": {\n    \"code\": 429,\n    \"message\": \"Insufficient tokens for quota 'WriteGroup' and limit 'USER-100s' of service 'sheets.googleapis.com' for consumer 'project_number:915324907459'.\",\n    \"status\": \"RESOURCE_EXHAUSTED\",\n    \"details\": [\n      {\n        \"@type\": \"type.googleapis.com/google.rpc.Help\",\n        \"links\": [\n          {\n            \"description\": \"Google developer console API key\",\n            \"url\": \"https://console.developers.google.com/project/915324907459/apiui/credential\"\n          }\n        ]\n      }\n    ]\n  }\n}\n", headers: [{"Vary", "X-Origin"}, {"Vary", "Referer"}, {"Content-Type", "application/json; charset=UTF-8"}, {"Date", "Thu, 06 Jul 2017 21:17:43 GMT"}, {"Server", "ESF"}, {"Cache-Control", "private"}, {"X-XSS-Protection", "1; mode=block"}, {"X-Frame-Options", "SAMEORIGIN"}, {"Alt-Svc", "quic=\":443\"; ma=2592000; v=\"39,38,37,36,35\""}, {"Accept-Ranges", "none"}, {"Vary", "Origin,Accept-Encoding"}, {"Transfer-Encoding", "chunked"}], request_url: "https://sheets.googleapis.com/v4/spreadsheets/[DELETED]/values:batchClear?ranges=list2!A1:E1&ranges=list2!A2:E2", status_code: 429}}
ed"}], request_url: "https://sheets.googleapis.com/v4/spreadsheets/[DELETED]/values:batchClear?ranges=list2!A1:E1&ranges=list2!A2:E2", status_code: 429}}
                 (elixir_google_spreadsheets) lib/elixir_google_spreadsheets/spreadsheet.ex:465: GSS.Spreadsheet.spreadsheet_query_response/1
                 (elixir_google_spreadsheets) lib/elixir_google_spreadsheets/spreadsheet.ex:384: GSS.Spreadsheet.handle_call/3
                 (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
                 (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
                 (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

```
2) test clear batched for 2 rows (GSS.SpreadsheetTest)
     test/elixir_google_spreadsheets/spreadsheet_test.exs:75
     ** (exit) exited in: GenServer.call(#PID<0.357.0>, {:clear_row, 1, []}, 5000)
         ** (EXIT) an exception was raised:
             ** (WithClauseError) no with clause matching: {:ok, %HTTPoison.Response{body: "{\n  \"error\": {\n    \"code\": 429,\n    \"message\": \"Insufficient tokens for quota 'WriteGroup' and limit 'USER-100s' of service 'sheets.googleapis.com' for consumer 'project_number:915324907459'.\",\n    \"status\": \"RESOURCE_EXHAUSTED\",\n    \"details\": [\n      {\n        \"@type\": \"type.googleapis.com/google.rpc.Help\",\n        \"links\": [\n          {\n            \"description\": \"Google developer console API key\",\n            \"url\": \"https://console.developers.google.com/project/915324907459/apiui/credential\"\n          }\n        ]\n      }\n    ]\n  }\n}\n", headers: [{"Vary", "X-Origin"}, {"Vary", "Referer"}, {"Content-Type", "application/json; charset=UTF-8"}, {"Date", "Thu, 06 Jul 2017 21:17:43 GMT"}, {"Server", "ESF"}, {"Cache-Control", "private"}, {"X-XSS-Protection", "1; mode=block"}, {"X-Frame-Options", "SAMEORIGIN"}, {"Alt-Svc", "quic=\":443\"; ma=2592000; v=\"39,38,37,36,35\""}, {"Accept-Ranges", "none"}, {"Vary", "Origin,Accept-Encoding"}, {"Transfer-Encoding", "chunked"}], request_url: "https://sheets.googleapis.com/v4/spreadsheets/[DELETED]/values/A1:Z1:clear", status_code: 429}}
_code: 429}}
                 (elixir_google_spreadsheets) lib/elixir_google_spreadsheets/spreadsheet.ex:465: GSS.Spreadsheet.spreadsheet_query_response/1
                 (elixir_google_spreadsheets) lib/elixir_google_spreadsheets/spreadsheet.ex:316: GSS.Spreadsheet.handle_call/3
                 (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
                 (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
                 (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
     stacktrace:
       (elixir) lib/gen_server.ex:737: GenServer.call/3
       test/elixir_google_spreadsheets/spreadsheet_test.exs:20: GSS.SpreadsheetTest.cleanup_table/1
       test/elixir_google_spreadsheets/spreadsheet_test.exs:12: anonymous fn/1 in GSS.SpreadsheetTest.__ex_unit_setup_0/1
       (ex_unit) lib/ex_unit/on_exit_handler.ex:98: ExUnit.OnExitHandler.exec_callback/1
       (ex_unit) lib/ex_unit/on_exit_handler.ex:82: ExUnit.OnExitHandler.on_exit_runner_loop/0
```

**Comment by Kr00lIX** [comment]
Maybe, that happened when you are running all the tests periodically in a short period of time. Limit counters are not persisted, every time when the application launches them start from the beginning and overlapping limiters from previous tests. That can happen only for test env, but I can add persisting them to DETs if you want.

**Comment by Kr00lIX** [comment]
@Voronchuk I adjusted config for limiters set interval to 1 minute.

**Comment by Voronchuk** [comment]
I think it's fine now

**Pull request merged**
