### PR TITLE
Update httpoison and goth dependencies

### PR DESCRIPTION
**Pull request by alex88**
I've updated httpoison and goth dependencies, I'm currently testing if it works

### CODE REVIEW

**Comment by Voronchuk** [comment]
There were some issues with later versions of `hackney`, that's why it was defined strictly, I'll be glad to update if it works fine.

**Comment by alex88** [comment]
I'll let you know, I'm having currently issues trying to start the supervisor as part of my application tree instead in the code when I need it

**Comment by alex88** [comment]
I've tested the id, rows, read_row api an they all work fine

**Comment by Voronchuk** [comment]
I'm still getting `{:error, %HTTPoison.Error{id: nil, reason: {:tls_alert, 'handshake failure'}}}` in all later versions of `Goth` library, I guess it's because of missing `[ssl: [{:versions, [:'tlsv1.2']}]]` in HTTPoison requests, so I'm leaving it as is for now.

**Pull request merged**
